defaults:
  - _self_

exp:
  seed: 1
  log_dir: # set during runtime to automatically created dir
  run_func: 
    _target_: experiment.run_points_near_class_boundary
  perturbation: 0.1 # The magnitude of the perturbation to be applied
  save_images: True   # To indicate if images should be saved
  grad_steps: 3

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: gpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}

network:
  _target_: network.MLP
  activation_fnc:
    _target_: torch.nn.ReLU
  layers: [784,200,200,200,200,200,10]
  model_path: ${oc.env:MODEL_DIR}/mnist_6_200_nat.pth

method:
  _partial_: True
  _target_: method.Composer
  plugins:
    - _target_: method.AffineNN
      epsilon: 0.015
      optimize_bounds: True
      gradient_iter: 100
      lr: 0.1
      
      

dataset:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: dataset.MNIST
    data_path: ${oc.env:DATA_DIR}/mnist
    train: false
    flatten: true
    no_points: 1000
  batch_size: 1

