defaults:
  - _self_

exp:
  seed: 1
  log_dir: # set during runtime to automatically created dir
  run_func: 
    _target_: experiment.run_get_output_bounds

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: gpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}

network:
  _target_: network.SDPModelLoader
  model_path: ${oc.env:MODEL_DIR}/cifar_cnn_a_mix4.model

method:
  _partial_: True
  _target_: method.Composer
  plugins:
    - _target_: method.AlphaCROWN
      epsilon: 0.00392156862 
      gradient_iter: 200
      lr: 0.1
      
      

_target_: torch.utils.data.DataLoader
dataset:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: dataset.CIFAR_SDP
    data_path: ${oc.env:DATA_DIR}/sdp/cifar
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.201]
  batch_size: 1
