defaults:
  - _self_

exp:
  seed: 1
  log_dir: # set during runtime to automatically created dir
  run_func: 
    _target_: experiment.run_salt_and_pepper
  amount: 0.2         # How much pixels are affected
  salt_vs_pepper: 0.5 # Ratio between salt and pepper
  save_images: True   # To indicate if deteriotated images should be saved

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: gpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}

network:
  _target_: network.ConvSmallCIFAR
  dim_out: 10
  model_path: ${oc.env:MODEL_DIR}/cifar_conv_small_pgd.pth

method:
  _partial_: True
  _target_: method.Composer
  plugins:
    - _target_: method.IBP
      epsilon: 0.00392156862 

dataset:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: dataset.CIFAR_ERAN
    data_path: ${oc.env:DATA_DIR}/cifar10
    train: false
    flatten: false
    no_points: 1000
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.201]
  batch_size: 1

