_partial_: True
_target_: method.Composer

plugins:
  - _target_: method.AffineNN
    epsilon: 0.015
    optimize_bounds: True
    gradient_iter: 100
    lr: 0.1
    lambda_valid: 1.0
    lambda_worst_case: 10.0