_target_: torch.utils.data.DataLoader

dataset:
  _target_: dataset.MNIST
  train:
    _target_: dataset.MNIST
    data_path: ./data
    train: true
    flatten: false
    split_ratio: [0.8, 0.2]  # 80% for training

  val:
    _target_: dataset.MNIST
    data_path: ./data
    train: true
    flatten: false
    split_ratio: [0.8, 0.2]  # 20% for validation

  test:
    _target_: dataset.MNIST
    data_path: ./data
    train: false
    flatten: false