dataset:
  train:
    _target_: torch.utils.data.DataLoader
    dataset:
      _target_: dataset.MNIST
      data_path: ./data/mnist
      train: true
      flatten: false
      split_ratio: [0.8, 0.2]
    batch_size: 4
    shuffle: true
    num_workers: 4

  val:
    _target_: torch.utils.data.DataLoader
    dataset:
      _target_: dataset.MNIST
      data_path: ./data/mnist
      train: true
      flatten: false
      split_ratio: [0.8, 0.2]
    batch_size: 4
    shuffle: false
    num_workers: 4

  test:
    _target_: torch.utils.data.DataLoader
    dataset:
      _target_: dataset.MNIST
      data_path: ./data/mnist
      train: false
      flatten: false
    batch_size: 4
    shuffle: false
    num_workers: 4
