defaults:
  - _self_

exp:
  seed: 1
  log_dir: # set during runtime to automatically created dir
  run_func: 
    _target_: experiment.run_get_output_bounds

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: gpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}

network:
  _target_: network.SDPModelLoader
  model_path: ${oc.env:MODEL_DIR}/mnist_cnn_a_adv.model

method:
  _partial_: True
  _target_: method.Composer
  plugins:
    - _target_: method.CROWN
      epsilon: 0.3
      
      

_target_: torch.utils.data.DataLoader
dataset:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: dataset.MNIST_SDP
    data_path: ${oc.env:DATA_DIR}/sdp/mnist
  batch_size: 1
