__partial__: True

seed: 42
log_dir: # set during runtime to automatically created dir
run_func: 
  _target_: experiment.run_salt_and_pepper
amount: 0.2         # How much pixels are affected
salt_vs_pepper: 0.5 # Ratio between salt and pepper
save_images: True   # To indicate if deteriotated images should be saved
