defaults:
  - _self_

method:
  _partial_: True
  _target_: method.Composer

  plugins:
    - _target_: method.AffineNN
      epsilon: 0.4
      optimize_bounds: False
      gradient_iter: 1
      lr: 0.1

exp:
  __partial__: True

  seed: 42
  log_dir: # set during runtime to automatically created dir
  run_func: 
    _target_: experiment.run_training

training:
  start_warmup_epoch: 0
  end_warmup_epoch: 1
  schedule_epochs_after_warmup: 60
  epochs: 100
  lr: 0.0005
  use_scheduler: False

network:
  _target_: network.ConvSmallB
  in_channels: 1
  dim_out: 10
  input_width: 28
  input_height: 28

dataset:
  dataset:
    train:
      _target_: torch.utils.data.DataLoader
      dataset:
        _target_: dataset.MNIST
        data_path: ./data/mnist
        train: true
        flatten: false
        split_ratio: [0.8, 0.2]
      batch_size: 4
      shuffle: true
      num_workers: 4

    val:
      _target_: torch.utils.data.DataLoader
      dataset:
        _target_: dataset.MNIST
        data_path: ./data/mnist
        train: true
        flatten: false
        split_ratio: [0.8, 0.2]
      batch_size: 4
      shuffle: false
      num_workers: 4

    test:
      _target_: torch.utils.data.DataLoader
      dataset:
        _target_: dataset.MNIST
        data_path: ./data/mnist
        train: false
        flatten: false
      batch_size: 4
      shuffle: false
      num_workers: 4


fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: cpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}